stages:
  - sync-git

sync-git:
  stage: sync-git
  image: registry.saas.hand-china.com/tools/devops-ci:1.1.0
  script:
    - mkdir -p ~/.ssh
    - echo ${choerodonci} > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git remote add home "${USERNAME}@choerodon.io:/home/${USERNAME}/git/choerodon/website"
    - sleep 100000
    - git push home master
  only:
    - master