baseurl = "http://choerodon.io/"
title = "Choerodon | 企业级数字服务平台"
theme = "hugo-choerodon-theme"
# themesDir = "../.."
#languageCode = "en-us"
languageCode = "zh-cn"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
prettyurls=true
# Define the number of posts per page
paginate = 10

[menu]
# Main menu
[[languages.en.menu.main]]
    name = "Docs"
    url  = "/docs/"
    weight = 1

[[languages.en.menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[languages.en.menu.main]]
    name = "Case Studies"
    url  = "/case-studies/"
    weight = 3

[[languages.en.menu.main]]
    name = "Community"
    url  = "/community/"
    weight = 4

[[languages.en.menu.main]]
    name = "Github"
    url  = "https://github.com/choerodon/choerodon"
    weight = 5
    post= true

[[languages.zh.menu.main]]
    name = "文档"
    url  = "/docs/"
    weight = 1

[[languages.zh.menu.main]]
    name = "博客"
    url  = "/blog/"
    weight = 2

[[languages.zh.menu.main]]
    name = "案例"
    url  = "/case-studies/"
    weight = 3

[[languages.zh.menu.main]]
    name = "社区"
    url  = "/community/"
    weight = 4

[[languages.zh.menu.main]]
    name = "Github"
    url  = "https://github.com/choerodon/"
    weight = 5
    post= true

[params]
    viewMorePostLink = "/blog/"
    author = "Choerodon"
    defaultKeywords = ["devops"]
    defaultDescription = ""
    # Format dates with Go's time formatting
    date_format = "2006-01-02"